### ISSUE TITLE
If player name too long they dont get marked

### ISSUE THREAD

**Issue by ghost** [LockonS483/AutoJailMarker#4]
If a player name is to long and gets shortened with ..., that player wont be marked.

**Comment by LockonS483** [comment]
The plugin should mark based on displayed name in your UI so adding the '...' to the priority config as displayed in your party list should work. Please give that a try!

**Comment by Bleyez** [comment]
Hey i'm having the same problem. The update for EW works but if a player has ... at the end of their name it won't mark them. I tried it like the plugin partylist shows and i tried putting in their full name, neither works.

**Comment by LockonS483** [comment]
Hey sorry I haven't had a chance to play with people with ... in their names. Can you try using only their first name or only their last name and see if that works? I will look into it myself if can find some ppl to test this with. Thanks!

**Comment by Heinzen** [comment]
Do you have any updates? Had lots of issues in uwu lately and I did not realize this was a defect. Alternatively, could you suggest which files to look into collecting names as I might be able to write a PR?

**Comment by LockonS483** [comment]
I haven't been able to put together a team to test stuff so far but you are free to try to figure it yourself! I think party list is matched and checked in ExecuteMarkers in Plugin.cs. The names are grabbed from the UI so i assumed if you typed in the names as it appears (i.e. firstname long...) instead of (i.e. firstname longlastname) it should work.

I will try to get some people together to try it out if i get a chance
